# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: ShenzhenHezonLitoTechnologyCo.,Ltd.VKTabletDriver
PackageVersion: 2.1.4.1
PackageLocale: en-US
Publisher: Shenzhen Hezon Lito Technology Co.,Ltd.
PackageName: VKTabletDriver
License: CDL
Copyright: Copyright(c) 2017-2022 VEIKK,All Right Reserved.
ShortDescription: VKTabletDriver Setup
ManifestType: defaultLocale
ManifestVersion: 1.5.0
